#import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetbrainsMono Nerd Font"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000

[window]
dynamic_title = true
opacity = 1
title = "Terminal"

[window.dimensions]
columns = 180
lines = 60

[window.padding]
x = 3
y = 3

[window.position]
x = 500
y = 100

# [colors.bright]
# black = "0x665c54"
# blue = "0xbdae93"
# cyan = "0xd65d0e"
# green = "0x3c3836"
# magenta = "0xebdbb2"
# red = "0xfe8019"
# white = "0xfbf1c7"
# yellow = "0x504945"
#
# [colors.cursor]
# cursor = "0xd5c4a1"
# text = "0x1d2021"
#
# [colors.normal]
# black = "0x1d2021"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xd5c4a1"
# yellow = "0xfabd2f"
#
# [colors.primary]
# background = "0x1d2021"
# foreground = "0xd5c4a1"
